# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1da8d5370caa0221b0572ddf16b60d92e06a65903f47baca282314a4c3abe7f4d8305340145ce0871a204ac00f9a221cdab77de7c831eed39ab62f6a0a540e1b

test:
  secret_key_base: cf63c331e46373a1002ee37e8c36979df6d8c8119ea87c195a5be62680e74ad431dd8d7cc6a30cab01783497baae09aa9e0841026055aed303f41e2b7ed89ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
